<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class WebsiteServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'title' => 'Billboards',
                'slug' => 'billboards',
                'excerpt' => 'High-impact outdoor advertising that gives your brand maximum visibility.',
                'description' => '<p>High-impact outdoor advertising that gives your brand maximum visibility.</p>',
                'image' => 'inc/assets/images/service-img-01.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Shop Branding',
                'slug' => 'shop-branding',
                'excerpt' => 'Transform your shopfront into a strong and professional brand statement.',
                'description' => '<p>Transform your shopfront into a strong and professional brand statement.</p>',
                'image' => 'inc/assets/images/service-img-02.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'Car Branding',
                'slug' => 'car-branding',
                'excerpt' => 'Turn every journey into a moving advert with bold vehicle branding.',
                'description' => '<p>Turn every journey into a moving advert with bold vehicle branding.</p>',
                'image' => 'inc/assets/images/service-img-03.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'Banners',
                'slug' => 'banners',
                'excerpt' => 'Custom banners designed to promote your business, campaign, or event.',
                'description' => '<p>Custom banners designed to promote your business, campaign, or event.</p>',
                'image' => 'inc/assets/images/service-img-04.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'Wall Panels',
                'slug' => 'wall-panels',
                'excerpt' => 'Stylish wall branding solutions for offices, shops, and commercial spaces.',
                'description' => '<p>Stylish wall branding solutions for offices, shops, and commercial spaces.</p>',
                'image' => 'inc/assets/images/service-img-05.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Maps & Blueprints',
                'slug' => 'maps-blueprints',
                'excerpt' => 'Clear, professional large-format printing for plans, maps, and technical drawings.',
                'description' => '<p>Clear, professional large-format printing for plans, maps, and technical drawings.</p>',
                'image' => 'inc/assets/images/service-img-06.jpg',
                'icon' => null,
                'category' => 'printing',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => true,
                'show_in_navbar' => true,
                'is_active' => true,
                'sort_order' => 6,
            ],

            [
                'title' => 'Sublimation Printing',
                'slug' => 'sublimation-printing',
                'excerpt' => 'High-quality full-colour printing for apparel and promotional items.',
                'description' => '<p>High-quality full-colour printing for apparel and promotional items.</p>',
                'image' => 'inc/assets/images/fact-img-1.jpg',
                'icon' => null,
                'category' => 'promo',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Screen Printing',
                'slug' => 'screen-printing',
                'excerpt' => 'Durable and cost-effective printing for bulk garments and branding.',
                'description' => '<p>Durable and cost-effective printing for bulk garments and branding.</p>',
                'image' => 'inc/assets/images/fact-img-2.jpg',
                'icon' => null,
                'category' => 'promo',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'title' => 'Embroidery Printing',
                'slug' => 'embroidery-printing',
                'excerpt' => 'Premium stitched branding for uniforms and corporate wear.',
                'description' => '<p>Premium stitched branding for uniforms and corporate wear.</p>',
                'image' => 'inc/assets/images/fact-img-3.jpg',
                'icon' => null,
                'category' => 'promo',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'title' => 'Corporate Gifts',
                'slug' => 'corporate-gifts',
                'excerpt' => 'Branded items like diaries, pens, bags, and promotional giveaways.',
                'description' => '<p>Branded items like diaries, pens, bags, and promotional giveaways.</p>',
                'image' => 'inc/assets/images/fact-img-4.jpg',
                'icon' => null,
                'category' => 'promo',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],

            [
                'title' => 'Search Engine Optimisation (SEO)',
                'slug' => 'seo',
                'excerpt' => 'Improve your visibility in search results and help more customers find your business online.',
                'description' => '<p>Improve your visibility in search results and help more customers find your business online.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'title' => 'Pay Per Click Advertising (PPC)',
                'slug' => 'ppc',
                'excerpt' => 'Run targeted paid campaigns that bring traffic, leads, and conversions.',
                'description' => '<p>Run targeted paid campaigns that bring traffic, leads, and conversions.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'title' => 'Web Design',
                'slug' => 'web-design',
                'excerpt' => 'Modern websites designed to present your brand professionally and drive business growth.',
                'description' => '<p>Modern websites designed to present your brand professionally and drive business growth.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'title' => 'Content Marketing',
                'slug' => 'content-marketing',
                'excerpt' => 'Create content that informs, attracts, and builds trust with your audience.',
                'description' => '<p>Create content that informs, attracts, and builds trust with your audience.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'title' => 'Social Media Marketing',
                'slug' => 'social-media-marketing',
                'excerpt' => 'Grow your presence, engagement, and customer reach on social platforms.',
                'description' => '<p>Grow your presence, engagement, and customer reach on social platforms.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'title' => 'Email Marketing & Google Business',
                'slug' => 'email-marketing-google-business',
                'excerpt' => 'Strengthen customer communication and boost your local online visibility.',
                'description' => '<p>Strengthen customer communication and boost your local online visibility.</p>',
                'image' => null,
                'icon' => null,
                'category' => 'digital',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 25,
            ],

            [
                'title' => 'Logo Design',
                'slug' => 'logo-design',
                'excerpt' => 'Professional logo design for strong and memorable brand identity.',
                'description' => '<p>We turn your ideas into professional visual concepts that strengthen your brand identity and communication.</p><p>• Logo design</p><p>• Flyers and sticker design</p><p>• Advertising materials, banners, and promotional visuals</p><p>• Business cards and brochures</p><p>• Company profiles</p>',
                'image' => 'inc/assets/images/tab-img-01.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Graphic Design',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'title' => 'Flyers and Sticker Design',
                'slug' => 'flyers-sticker-design',
                'excerpt' => 'Creative designs for flyers, stickers, and promotional materials.',
                'description' => '<p>Creative designs for flyers, stickers, and promotional materials.</p>',
                'image' => 'inc/assets/images/tab-img-01.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Graphic Design',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'title' => 'Business Cards and Brochures',
                'slug' => 'business-cards-brochures',
                'excerpt' => 'Professional print-ready designs for cards, brochures, and corporate marketing materials.',
                'description' => '<p>Professional print-ready designs for cards, brochures, and corporate marketing materials.</p>',
                'image' => 'inc/assets/images/tab-img-01.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Graphic Design',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'title' => 'Company Profiles',
                'slug' => 'company-profiles',
                'excerpt' => 'Well-designed company profiles that present your business professionally.',
                'description' => '<p>Well-designed company profiles that present your business professionally.</p>',
                'image' => 'inc/assets/images/tab-img-01.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Graphic Design',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 33,
            ],

            [
                'title' => 'Page Creation and Setup',
                'slug' => 'page-creation-setup',
                'excerpt' => 'Professional setup of social media pages for your business.',
                'description' => '<p>We help businesses build a strong online presence through strategic content creation, campaign management, and audience engagement.</p><p>• Page creation and setup</p><p>• Facebook and Google advertising</p><p>• Content creation and account management</p><p>• Targeted lead generation</p><p>• Social media strategy development</p>',
                'image' => 'inc/assets/images/tab-img-02.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Social Media Management',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'title' => 'Facebook and Google Advertising',
                'slug' => 'facebook-google-advertising',
                'excerpt' => 'Targeted advertising campaigns that increase visibility and results.',
                'description' => '<p>Targeted advertising campaigns that increase visibility and results.</p>',
                'image' => 'inc/assets/images/tab-img-02.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Social Media Management',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'title' => 'Content Creation and Account Management',
                'slug' => 'content-creation-account-management',
                'excerpt' => 'Consistent content and professional management of your online accounts.',
                'description' => '<p>Consistent content and professional management of your online accounts.</p>',
                'image' => 'inc/assets/images/tab-img-02.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Social Media Management',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'title' => 'Targeted Lead Generation',
                'slug' => 'targeted-lead-generation',
                'excerpt' => 'Generate quality leads through focused social and digital campaigns.',
                'description' => '<p>Generate quality leads through focused social and digital campaigns.</p>',
                'image' => 'inc/assets/images/tab-img-02.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Social Media Management',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 43,
            ],

            [
                'title' => 'Company Registration',
                'slug' => 'company-registration',
                'excerpt' => 'Practical support to help businesses formally establish themselves.',
                'description' => '<p>We provide practical business support services that help organisations establish, grow, and operate more effectively.</p><p>• Company registration</p><p>• Sales training and consultancy</p><p>• Public relations consultancy</p><p>• Business development and marketing consultancy</p>',
                'image' => 'inc/assets/images/tab-img-03.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Business Services',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'title' => 'Sales Training and Consultancy',
                'slug' => 'sales-training-consultancy',
                'excerpt' => 'Support your team with practical sales and performance improvement training.',
                'description' => '<p>Support your team with practical sales and performance improvement training.</p>',
                'image' => 'inc/assets/images/tab-img-03.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Business Services',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'title' => 'Public Relations Consultancy',
                'slug' => 'public-relations-consultancy',
                'excerpt' => 'Professional support to strengthen public image and communication.',
                'description' => '<p>Professional support to strengthen public image and communication.</p>',
                'image' => 'inc/assets/images/tab-img-03.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Business Services',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'title' => 'Business Development and Marketing Consultancy',
                'slug' => 'business-development-marketing-consultancy',
                'excerpt' => 'Expert help to grow, position, and market your business effectively.',
                'description' => '<p>Expert help to grow, position, and market your business effectively.</p>',
                'image' => 'inc/assets/images/tab-img-03.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Business Services',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 53,
            ],

            [
                'title' => 'Customised Solutions',
                'slug' => 'customised-solutions',
                'excerpt' => 'Every quotation is prepared based on your exact requirements.',
                'description' => '<p>Our pricing is tailored to the specific products and services selected by each client.</p><p><strong>Customised Solutions:</strong> Every quotation is prepared based on your exact requirements to ensure you receive the most suitable solution for your business.</p><p><strong>Quality Assurance:</strong> We are committed to providing courteous, prompt, and dependable service, supported by high-quality products and professional execution.</p><p><strong>Reliability:</strong> We strive to keep costs competitive without compromising quality.</p><p>Contact our marketing executive for a quotation on <strong>0772 610 975</strong> or email us at <strong>admin@mcmupahmarketing.co.zw</strong>.</p>',
                'image' => 'inc/assets/images/tab-img-04.jpg',
                'icon' => null,
                'category' => 'other',
                'group_name' => 'Pricing & Value',
                'button_text' => 'LEARN MORE',
                'button_link' => '#contact',
                'client_link' => null,
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 60,
            ],

            [
                'title' => 'Trade Reference 1',
                'slug' => 'trade-reference-1',
                'excerpt' => null,
                'description' => null,
                'image' => 'inc/assets/images/client-logo.png',
                'icon' => null,
                'category' => 'trade_reference',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => '#',
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'title' => 'Trade Reference 2',
                'slug' => 'trade-reference-2',
                'excerpt' => null,
                'description' => null,
                'image' => 'inc/assets/images/client-logo1.png',
                'icon' => null,
                'category' => 'trade_reference',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => '#',
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 71,
            ],
            [
                'title' => 'Trade Reference 3',
                'slug' => 'trade-reference-3',
                'excerpt' => null,
                'description' => null,
                'image' => 'inc/assets/images/client-logo2.png',
                'icon' => null,
                'category' => 'trade_reference',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => '#',
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 72,
            ],
            [
                'title' => 'Trade Reference 4',
                'slug' => 'trade-reference-4',
                'excerpt' => null,
                'description' => null,
                'image' => 'inc/assets/images/client-logo3.png',
                'icon' => null,
                'category' => 'trade_reference',
                'group_name' => null,
                'button_text' => null,
                'button_link' => null,
                'client_link' => '#',
                'show_on_home' => false,
                'show_in_navbar' => false,
                'is_active' => true,
                'sort_order' => 73,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['slug' => $service['slug']],
                $service
            );
        }
    }
}